---
# tasks file for webservers

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
- name: 'Disable firewalld Services'
  service:
    name: ufw
    state: stopped  
    enabled: no
